In [1]:
import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print('ran')

ran

In [3]:
bureau=pd.read_csv("C:\\Users\\dbda\\Desktop\\bureau.csv")
print("Shape of training data: {}".format(bureau.shape))

Shape of training data: (1716428, 17)

In [7]:
bureau.drop('SK_ID_CURR', inplace=True, axis=1)
bureau.drop('SK_ID_BUREAU', inplace=True, axis=1)
print("Shape of training data: {}".format(bureau.shape))

Shape of training data: (1716428, 15)

In [8]:
df = pd.DataFrame(bureau)

In [9]:
df

,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.000,0.000,NaN,0.0,Consumer credit,-131,NaN
1,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.000,171342.000,NaN,0.0,Credit card,-20,NaN
2,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.500,NaN,NaN,0.0,Consumer credit,-16,NaN
3,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.000,NaN,NaN,0.0,Credit card,-16,NaN
4,Active,currency 1,-629,0,1197.0,NaN,77674.500,0,2700000.000,NaN,NaN,0.0,Consumer credit,-21,NaN
5,Active,currency 1,-273,0,27460.0,NaN,0.000,0,180000.000,71017.380,108982.620,0.0,Credit card,-31,NaN
6,Active,currency 1,-43,0,79.0,NaN,0.000,0,42103.800,42103.800,0.000,0.0,Consumer credit,-22,NaN
7,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.000,0,76878.450,0.000,0.000,0.0,Consumer credit,-1710,NaN
8,Closed,currency 1,-1146,0,-811.0,-840.0,0.000,0,103007.700,0.000,0.000,0.0,Consumer credit,-840,NaN
9,Active,currency 1,-1146,0,-484.0,NaN,0.000,0,4500.000,0.000,0.000,0.0,Credit card,-690,NaN
10,Active,currency 1,-1146,0,-180.0,NaN,0.000,0,337500.000,0.000,0.000,0.0,Credit card,-690,NaN
11,Closed,currency 1,-2456,0,-629.0,-825.0,NaN,0,675000.000,0.000,0.000,0.0,Consumer credit,-706,NaN
12,Active,currency 1,-277,0,5261.0,NaN,0.000,0,7033500.000,NaN,NaN,0.0,Mortgage,-31,NaN
13,Active,currency 1,-96,0,269.0,NaN,0.000,0,89910.000,76905.000,0.000,0.0,Consumer credit,-22,NaN
14,Closed,currency 1,-318,0,-187.0,-187.0,NaN,0,0.000,0.000,0.000,0.0,Credit card,-185,NaN
15,Closed,currency 1,-2911,0,-2607.0,-2604.0,NaN,0,48555.000,NaN,NaN,0.0,Consumer credit,-2601,NaN
16,Closed,currency 1,-2148,0,-1595.0,-987.0,NaN,0,135000.000,NaN,NaN,0.0,Consumer credit,-984,NaN
17,Active,currency 1,-381,0,NaN,NaN,NaN,0,450000.000,520920.000,NaN,0.0,Consumer credit,-4,NaN
18,Active,currency 1,-95,0,1720.0,NaN,NaN,0,67500.000,8131.500,NaN,0.0,Credit card,-7,NaN
19,Closed,currency 1,-444,0,-77.0,-77.0,0.000,0,107184.060,0.000,0.000,0.0,Consumer credit,-71,NaN
20,Active,currency 1,-392,0,NaN,NaN,0.000,0,252000.000,23679.000,228320.100,0.0,Credit card,-22,NaN
21,Active,currency 1,-784,0,1008.0,NaN,0.000,0,0.000,-411.615,411.615,0.0,Credit card,-694,NaN
22,Active,currency 1,-774,0,625.0,NaN,NaN,0,127840.500,0.000,0.000,0.0,Credit card,-210,NaN
23,Active,currency 1,-395,0,1431.0,NaN,NaN,0,1350000.000,1185493.500,0.000,0.0,Consumer credit,-24,NaN
24,Closed,currency 1,-2744,0,-2561.0,-2559.0,310.500,0,18157.500,NaN,NaN,0.0,Consumer credit,-2559,NaN
25,Closed,currency 1,-1103,0,-7.0,-343.0,20493.270,0,675000.000,0.000,0.000,0.0,Consumer credit,-343,NaN
26,Active,currency 1,-315,0,1512.0,NaN,88821.000,0,3709552.500,NaN,NaN,0.0,Car loan,-32,NaN
27,Closed,currency 1,-1331,0,-994.0,-1023.0,1350.000,0,39433.500,0.000,0.000,0.0,Consumer credit,-1023,NaN
28,Closed,currency 1,-2534,0,-2352.0,-2347.0,NaN,0,38830.500,0.000,0.000,0.0,Consumer credit,-2345,NaN
29,Closed,currency 1,-845,0,-480.0,-480.0,0.000,0,67500.000,0.000,0.000,0.0,Consumer credit,-480,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716398,Closed,currency 1,-1529,0,-829.0,-829.0,NaN,0,209898.000,0.000,NaN,0.0,Consumer credit,-824,NaN
1716399,Active,currency 1,-613,0,721.0,NaN,NaN,0,972000.000,886297.500,0.000,0.0,Credit card,-42,NaN
1716400,Active,currency 1,-815,0,1011.0,NaN,NaN,0,147150.000,105358.500,0.000,0.0,Consumer credit,-70,NaN
1716401,Closed,currency 1,-2333,0,-2027.0,-1984.0,173.070,0,35032.500,0.000,0.000,0.0,Consumer credit,-1984,NaN
1716402,Closed,currency 1,-1714,0,-1530.0,-1564.0,NaN,0,35271.000,0.000,0.000,0.0,Consumer credit,-1532,NaN
1716403,Active,currency 1,-765,0,1061.0,NaN,NaN,0,1431000.000,1092226.500,0.000,0.0,Consumer credit,-126,NaN
1716404,Active,currency 1,-99,0,997.0,NaN,0.000,0,450000.000,432787.500,0.000,0.0,Consumer credit,-7,NaN
1716405,Closed,currency 1,-2390,0,-2053.0,-2082.0,11317.590,0,112204.350,0.000,0.000,0.0,Consumer credit,-2082,NaN
1716406,Closed,currency 1,-2517,0,-660.0,-2363.0,0.000,0,473940.000,0.000,0.000,0.0,Car loan,-2363,NaN
1716407,Closed,currency 1,-1990,0,-1244.0,-1248.0,NaN,0,90000.000,NaN,NaN,0.0,Consumer credit,-1248,NaN
1716408,Closed,currency 1,-434,0,-344.0,-344.0,NaN,0,234000.000,0.000,NaN,0.0,Credit card,-336,NaN
1716409,Closed,currency 1,-1705,0,-582.0,-582.0,0.000,0,0.000,0.000,0.000,0.0,Credit card,-582,NaN
1716410,Active,currency 1,-575,0,813.0,NaN,NaN,0,67500.000,0.000,0.000,0.0,Credit card,-46,NaN
1716411,Closed,currency 1,-821,0,-425.0,-545.0,0.000,0,108765.720,0.000,0.000,0.0,Consumer credit,-545,NaN
1716412,Active,currency 1,-541,0,7.0,NaN,NaN,0,225000.000,10971.000,0.000,0.0,Consumer credit,-11,NaN
1716413,Closed,currency 1,-463,0,-36.0,-36.0,6863.715,0,110878.470,0.000,0.000,0.0,Consumer credit,-33,NaN
1716414,Closed,currency 1,-1628,0,-1320.0,-1320.0,5693.625,0,57834.000,0.000,0.000,0.0,Consumer credit,-1320,NaN
1716415,Closed,currency 1,-1970,0,-1577.0,-1577.0,NaN,0,93955.500,NaN,NaN,0.0,Consumer credit,-1577,NaN
1716416,Closed,currency 1,-1100,0,-732.0,-731.0,NaN,0,98775.000,0.000,0.000,0.0,Consumer credit,-720,NaN
1716417,Active,currency 1,-740,0,31128.0,NaN,NaN,0,67500.000,2466.000,NaN,0.0,Credit card,-433,NaN
1716418,Closed,currency 1,-1389,0,-1299.0,-1299.0,0.000,0,334158.435,0.000,0.000,0.0,Consumer credit,-1299,NaN
1716419,Closed,currency 1,-1808,0,-1596.0,-1625.0,8100.000,0,28248.840,0.000,0.000,0.0,Consumer credit,-1625,NaN
1716420,Closed,currency 1,-99,0,-83.0,-98.0,NaN,0,27000.000,0.000,0.000,0.0,Consumer credit,-18,NaN
1716421,Closed,currency 1,-1335,0,-1152.0,-1152.0,NaN,0,195408.000,0.000,NaN,0.0,Consumer credit,-1139,NaN
1716422,Closed,currency 1,-2648,0,31129.0,-189.0,NaN,0,202500.000,0.000,NaN,0.0,Credit card,-109,NaN
1716423,Active,currency 1,-44,0,-30.0,NaN,0.000,0,11250.000,11250.000,0.000,0.0,Microloan,-19,NaN
1716424,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.500,0,38130.840,0.000,0.000,0.0,Consumer credit,-2493,NaN
1716425,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.000,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.000,0.000,0.000,0.0,Consumer credit,-1508,NaN
1716427,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.000,0.000,NaN,0.0,Microloan,-387,NaN

In [11]:
df['CREDIT_ACTIVE'] =df['CREDIT_ACTIVE'].astype('category').cat.codes
df['CREDIT_CURRENCY'] =df['CREDIT_CURRENCY'].astype('category').cat.codes
df['CREDIT_TYPE'] =df['CREDIT_TYPE'].astype('category').cat.codes

In [14]:
df

,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,2,0,-497,0,-153.0,-153.0,NaN,0,91323.000,0.000,NaN,0.0,3,-131,NaN
1,0,0,-208,0,1075.0,NaN,NaN,0,225000.000,171342.000,NaN,0.0,4,-20,NaN
2,0,0,-203,0,528.0,NaN,NaN,0,464323.500,NaN,NaN,0.0,3,-16,NaN
3,0,0,-203,0,NaN,NaN,NaN,0,90000.000,NaN,NaN,0.0,4,-16,NaN
4,0,0,-629,0,1197.0,NaN,77674.500,0,2700000.000,NaN,NaN,0.0,3,-21,NaN
5,0,0,-273,0,27460.0,NaN,0.000,0,180000.000,71017.380,108982.620,0.0,4,-31,NaN
6,0,0,-43,0,79.0,NaN,0.000,0,42103.800,42103.800,0.000,0.0,3,-22,NaN
7,2,0,-1896,0,-1684.0,-1710.0,14985.000,0,76878.450,0.000,0.000,0.0,3,-1710,NaN
8,2,0,-1146,0,-811.0,-840.0,0.000,0,103007.700,0.000,0.000,0.0,3,-840,NaN
9,0,0,-1146,0,-484.0,NaN,0.000,0,4500.000,0.000,0.000,0.0,4,-690,NaN
10,0,0,-1146,0,-180.0,NaN,0.000,0,337500.000,0.000,0.000,0.0,4,-690,NaN
11,2,0,-2456,0,-629.0,-825.0,NaN,0,675000.000,0.000,0.000,0.0,3,-706,NaN
12,0,0,-277,0,5261.0,NaN,0.000,0,7033500.000,NaN,NaN,0.0,12,-31,NaN
13,0,0,-96,0,269.0,NaN,0.000,0,89910.000,76905.000,0.000,0.0,3,-22,NaN
14,2,0,-318,0,-187.0,-187.0,NaN,0,0.000,0.000,0.000,0.0,4,-185,NaN
15,2,0,-2911,0,-2607.0,-2604.0,NaN,0,48555.000,NaN,NaN,0.0,3,-2601,NaN
16,2,0,-2148,0,-1595.0,-987.0,NaN,0,135000.000,NaN,NaN,0.0,3,-984,NaN
17,0,0,-381,0,NaN,NaN,NaN,0,450000.000,520920.000,NaN,0.0,3,-4,NaN
18,0,0,-95,0,1720.0,NaN,NaN,0,67500.000,8131.500,NaN,0.0,4,-7,NaN
19,2,0,-444,0,-77.0,-77.0,0.000,0,107184.060,0.000,0.000,0.0,3,-71,NaN
20,0,0,-392,0,NaN,NaN,0.000,0,252000.000,23679.000,228320.100,0.0,4,-22,NaN
21,0,0,-784,0,1008.0,NaN,0.000,0,0.000,-411.615,411.615,0.0,4,-694,NaN
22,0,0,-774,0,625.0,NaN,NaN,0,127840.500,0.000,0.000,0.0,4,-210,NaN
23,0,0,-395,0,1431.0,NaN,NaN,0,1350000.000,1185493.500,0.000,0.0,3,-24,NaN
24,2,0,-2744,0,-2561.0,-2559.0,310.500,0,18157.500,NaN,NaN,0.0,3,-2559,NaN
25,2,0,-1103,0,-7.0,-343.0,20493.270,0,675000.000,0.000,0.000,0.0,3,-343,NaN
26,0,0,-315,0,1512.0,NaN,88821.000,0,3709552.500,NaN,NaN,0.0,1,-32,NaN
27,2,0,-1331,0,-994.0,-1023.0,1350.000,0,39433.500,0.000,0.000,0.0,3,-1023,NaN
28,2,0,-2534,0,-2352.0,-2347.0,NaN,0,38830.500,0.000,0.000,0.0,3,-2345,NaN
29,2,0,-845,0,-480.0,-480.0,0.000,0,67500.000,0.000,0.000,0.0,3,-480,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716398,2,0,-1529,0,-829.0,-829.0,NaN,0,209898.000,0.000,NaN,0.0,3,-824,NaN
1716399,0,0,-613,0,721.0,NaN,NaN,0,972000.000,886297.500,0.000,0.0,4,-42,NaN
1716400,0,0,-815,0,1011.0,NaN,NaN,0,147150.000,105358.500,0.000,0.0,3,-70,NaN
1716401,2,0,-2333,0,-2027.0,-1984.0,173.070,0,35032.500,0.000,0.000,0.0,3,-1984,NaN
1716402,2,0,-1714,0,-1530.0,-1564.0,NaN,0,35271.000,0.000,0.000,0.0,3,-1532,NaN
1716403,0,0,-765,0,1061.0,NaN,NaN,0,1431000.000,1092226.500,0.000,0.0,3,-126,NaN
1716404,0,0,-99,0,997.0,NaN,0.000,0,450000.000,432787.500,0.000,0.0,3,-7,NaN
1716405,2,0,-2390,0,-2053.0,-2082.0,11317.590,0,112204.350,0.000,0.000,0.0,3,-2082,NaN
1716406,2,0,-2517,0,-660.0,-2363.0,0.000,0,473940.000,0.000,0.000,0.0,1,-2363,NaN
1716407,2,0,-1990,0,-1244.0,-1248.0,NaN,0,90000.000,NaN,NaN,0.0,3,-1248,NaN
1716408,2,0,-434,0,-344.0,-344.0,NaN,0,234000.000,0.000,NaN,0.0,4,-336,NaN
1716409,2,0,-1705,0,-582.0,-582.0,0.000,0,0.000,0.000,0.000,0.0,4,-582,NaN
1716410,0,0,-575,0,813.0,NaN,NaN,0,67500.000,0.000,0.000,0.0,4,-46,NaN
1716411,2,0,-821,0,-425.0,-545.0,0.000,0,108765.720,0.000,0.000,0.0,3,-545,NaN
1716412,0,0,-541,0,7.0,NaN,NaN,0,225000.000,10971.000,0.000,0.0,3,-11,NaN
1716413,2,0,-463,0,-36.0,-36.0,6863.715,0,110878.470,0.000,0.000,0.0,3,-33,NaN
1716414,2,0,-1628,0,-1320.0,-1320.0,5693.625,0,57834.000,0.000,0.000,0.0,3,-1320,NaN
1716415,2,0,-1970,0,-1577.0,-1577.0,NaN,0,93955.500,NaN,NaN,0.0,3,-1577,NaN
1716416,2,0,-1100,0,-732.0,-731.0,NaN,0,98775.000,0.000,0.000,0.0,3,-720,NaN
1716417,0,0,-740,0,31128.0,NaN,NaN,0,67500.000,2466.000,NaN,0.0,4,-433,NaN
1716418,2,0,-1389,0,-1299.0,-1299.0,0.000,0,334158.435,0.000,0.000,0.0,3,-1299,NaN
1716419,2,0,-1808,0,-1596.0,-1625.0,8100.000,0,28248.840,0.000,0.000,0.0,3,-1625,NaN
1716420,2,0,-99,0,-83.0,-98.0,NaN,0,27000.000,0.000,0.000,0.0,3,-18,NaN
1716421,2,0,-1335,0,-1152.0,-1152.0,NaN,0,195408.000,0.000,NaN,0.0,3,-1139,NaN
1716422,2,0,-2648,0,31129.0,-189.0,NaN,0,202500.000,0.000,NaN,0.0,4,-109,NaN
1716423,0,0,-44,0,-30.0,NaN,0.000,0,11250.000,11250.000,0.000,0.0,10,-19,NaN
1716424,2,0,-2648,0,-2433.0,-2493.0,5476.500,0,38130.840,0.000,0.000,0.0,3,-2493,NaN
1716425,2,0,-1809,0,-1628.0,-970.0,NaN,0,15570.000,NaN,NaN,0.0,3,-967,NaN
1716426,2,0,-1878,0,-1513.0,-1513.0,NaN,0,36000.000,0.000,0.000,0.0,3,-1508,NaN
1716427,2,0,-463,0,NaN,-387.0,NaN,0,22500.000,0.000,NaN,0.0,10,-387,NaN

In [13]:
df[df.columns[1:]].corr()['AMT_CREDIT_SUM'][:]

CREDIT_CURRENCY           0.100223
DAYS_CREDIT               0.050883
CREDIT_DAY_OVERDUE       -0.003292
DAYS_CREDIT_ENDDATE       0.055424
DAYS_ENDDATE_FACT         0.059096
AMT_CREDIT_MAX_OVERDUE    0.081663
CNT_CREDIT_PROLONG       -0.008345
AMT_CREDIT_SUM            1.000000
AMT_CREDIT_SUM_DEBT       0.683419
AMT_CREDIT_SUM_LIMIT      0.003756
AMT_CREDIT_SUM_OVERDUE    0.006342
CREDIT_TYPE               0.286320
DAYS_CREDIT_UPDATE        0.104629
AMT_ANNUITY               0.049146
Name: AMT_CREDIT_SUM, dtype: float64