In [1]:
# numpy and pandas for data manipulation
import numpy as np
import pandas as pd 

# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder

# File system manangement
import os
from scipy import stats

# Suppress warnings 
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Testing data features
app_test = pd.read_csv('F:/Project/application_test.csv')
print('Testing data shape: ', app_test.shape)
app_test.head()

Testing data shape:  (48744, 121)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Bureau data features
bureau = pd.read_csv('F:/Project/bureau.csv')
print('bureau data shape: ', bureau.shape)
bureau.head()

bureau data shape:  (1716428, 17)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [4]:
# Bureau data features
bureau_balance = pd.read_csv('F:/Project/bureau_balance.csv')
print('bureau_balance data shape: ', bureau_balance.shape)
bureau_balance.head()

bureau_balance data shape:  (27299925, 3)

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [5]:
# joining bureau and bureau_balance
bureau = bureau.merge(bureau_balance, how='left', left_on='SK_ID_BUREAU', right_index=True)

In [6]:
bureau

,SK_ID_CURR,SK_ID_BUREAU_x,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_BUREAU_y,MONTHS_BALANCE,STATUS
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.000,0.000,NaN,0.0,Consumer credit,-131,NaN,6066882,-24,0
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.000,171342.000,NaN,0.0,Credit card,-20,NaN,6066882,-25,0
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.500,NaN,NaN,0.0,Consumer credit,-16,NaN,6066882,-26,0
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.000,NaN,NaN,0.0,Credit card,-16,NaN,6066884,0,C
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.500,0,2700000.000,NaN,NaN,0.0,Consumer credit,-21,NaN,6066884,-1,C
5,215354,5714467,Active,currency 1,-273,0,27460.0,NaN,0.000,0,180000.000,71017.380,108982.620,0.0,Credit card,-31,NaN,6066884,-2,C
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.000,0,42103.800,42103.800,0.000,0.0,Consumer credit,-22,NaN,6066884,-3,C
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.000,0,76878.450,0.000,0.000,0.0,Consumer credit,-1710,NaN,6066884,-4,C
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.000,0,103007.700,0.000,0.000,0.0,Consumer credit,-840,NaN,6066884,-5,C
9,162297,5714471,Active,currency 1,-1146,0,-484.0,NaN,0.000,0,4500.000,0.000,0.000,0.0,Credit card,-690,NaN,6066884,-6,C
10,162297,5714472,Active,currency 1,-1146,0,-180.0,NaN,0.000,0,337500.000,0.000,0.000,0.0,Credit card,-690,NaN,6066884,-7,C
11,162297,5714473,Closed,currency 1,-2456,0,-629.0,-825.0,NaN,0,675000.000,0.000,0.000,0.0,Consumer credit,-706,NaN,6066884,-8,C
12,162297,5714474,Active,currency 1,-277,0,5261.0,NaN,0.000,0,7033500.000,NaN,NaN,0.0,Mortgage,-31,NaN,6066884,-9,C
13,402440,5714475,Active,currency 1,-96,0,269.0,NaN,0.000,0,89910.000,76905.000,0.000,0.0,Consumer credit,-22,NaN,6066884,-10,C
14,238881,5714482,Closed,currency 1,-318,0,-187.0,-187.0,NaN,0,0.000,0.000,0.000,0.0,Credit card,-185,NaN,6066884,-17,C
15,238881,5714484,Closed,currency 1,-2911,0,-2607.0,-2604.0,NaN,0,48555.000,NaN,NaN,0.0,Consumer credit,-2601,NaN,6066884,-19,C
16,238881,5714485,Closed,currency 1,-2148,0,-1595.0,-987.0,NaN,0,135000.000,NaN,NaN,0.0,Consumer credit,-984,NaN,6066884,-20,C
17,238881,5714486,Active,currency 1,-381,0,NaN,NaN,NaN,0,450000.000,520920.000,NaN,0.0,Consumer credit,-4,NaN,6066884,-21,C
18,238881,5714487,Active,currency 1,-95,0,1720.0,NaN,NaN,0,67500.000,8131.500,NaN,0.0,Credit card,-7,NaN,6066884,-22,C
19,238881,5714488,Closed,currency 1,-444,0,-77.0,-77.0,0.000,0,107184.060,0.000,0.000,0.0,Consumer credit,-71,NaN,6066884,-23,C
20,238881,5714489,Active,currency 1,-392,0,NaN,NaN,0.000,0,252000.000,23679.000,228320.100,0.0,Credit card,-22,NaN,6066884,-24,C
21,222183,5714491,Active,currency 1,-784,0,1008.0,NaN,0.000,0,0.000,-411.615,411.615,0.0,Credit card,-694,NaN,6066884,-26,C
22,222183,5714492,Active,currency 1,-774,0,625.0,NaN,NaN,0,127840.500,0.000,0.000,0.0,Credit card,-210,NaN,6066884,-27,C
23,222183,5714493,Active,currency 1,-395,0,1431.0,NaN,NaN,0,1350000.000,1185493.500,0.000,0.0,Consumer credit,-24,NaN,6066884,-28,C
24,222183,5714495,Closed,currency 1,-2744,0,-2561.0,-2559.0,310.500,0,18157.500,NaN,NaN,0.0,Consumer credit,-2559,NaN,6066884,-30,C
25,222183,5714496,Closed,currency 1,-1103,0,-7.0,-343.0,20493.270,0,675000.000,0.000,0.000,0.0,Consumer credit,-343,NaN,6066884,-31,C
26,222183,5714497,Active,currency 1,-315,0,1512.0,NaN,88821.000,0,3709552.500,NaN,NaN,0.0,Car loan,-32,NaN,6066884,-32,C
27,426155,5714498,Closed,currency 1,-1331,0,-994.0,-1023.0,1350.000,0,39433.500,0.000,0.000,0.0,Consumer credit,-1023,NaN,6066884,-33,C
28,426155,5714499,Closed,currency 1,-2534,0,-2352.0,-2347.0,NaN,0,38830.500,0.000,0.000,0.0,Consumer credit,-2345,NaN,6066884,-34,C
29,426155,5714500,Closed,currency 1,-845,0,-480.0,-480.0,0.000,0,67500.000,0.000,0.000,0.0,Consumer credit,-480,NaN,6066884,-35,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716398,312021,5057541,Closed,currency 1,-1529,0,-829.0,-829.0,NaN,0,209898.000,0.000,NaN,0.0,Consumer credit,-824,NaN,5811918,-7,1
1716399,232638,5057553,Active,currency 1,-613,0,721.0,NaN,NaN,0,972000.000,886297.500,0.000,0.0,Credit card,-42,NaN,5811921,0,C
1716400,318662,5057561,Active,currency 1,-815,0,1011.0,NaN,NaN,0,147150.000,105358.500,0.000,0.0,Consumer credit,-70,NaN,5811921,-8,C
1716401,145715,5057569,Closed,currency 1,-2333,0,-2027.0,-1984.0,173.070,0,35032.500,0.000,0.000,0.0,Consumer credit,-1984,NaN,5811921,-16,C
1716402,352358,5057580,Closed,currency 1,-1714,0,-1530.0,-1564.0,NaN,0,35271.000,0.000,0.000,0.0,Consumer credit,-1532,NaN,5811921,-27,C
1716403,361928,5057589,Active,currency 1,-765,0,1061.0,NaN,NaN,0,1431000.000,1092226.500,0.000,0.0,Consumer credit,-126,NaN,5811921,-36,0
1716404,166279,5057599,Active,currency 1,-99,0,997.0,NaN,0.000,0,450000.000,432787.500,0.000,0.0,Consumer credit,-7,NaN,5811921,-46,0
1716405,438109,5057605,Closed,currency 1,-2390,0,-2053.0,-2082.0,11317.590,0,112204.350,0.000,0.000,0.0,Consumer credit,-2082,NaN,5811921,-52,0
1716406,335468,5057618,Closed,currency 1,-2517,0,-660.0,-2363.0,0.000,0,473940.000,0.000,0.000,0.0,Car loan,-2363,NaN,5811921,-65,X
1716407,146896,5057629,Closed,currency 1,-1990,0,-1244.0,-1248.0,NaN,0,90000.000,NaN,NaN,0.0,Consumer credit,-1248,NaN,5811921,-76,X
1716408,146896,5057632,Closed,currency 1,-434,0,-344.0,-344.0,NaN,0,234000.000,0.000,NaN,0.0,Credit card,-336,NaN,5811921,-79,X
1716409,146896,5057636,Closed,currency 1,-1705,0,-582.0,-582.0,0.000,0,0.000,0.000,0.000,0.0,Credit card,-582,NaN,5811921,-83,X
1716410,280228,5057642,Active,currency 1,-575,0,813.0,NaN,NaN,0,67500.000,0.000,0.000,0.0,Credit card,-46,NaN,5811922,-1,0
1716411,232118,5057652,Closed,currency 1,-821,0,-425.0,-545.0,0.000,0,108765.720,0.000,0.000,0.0,Consumer credit,-545,NaN,5811923,-5,0
1716412,288038,5057657,Active,currency 1,-541,0,7.0,NaN,NaN,0,225000.000,10971.000,0.000,0.0,Consumer credit,-11,NaN,5811923,-10,0
1716413,288038,5057665,Closed,currency 1,-463,0,-36.0,-36.0,6863.715,0,110878.470,0.000,0.000,0.0,Consumer credit,-33,NaN,5811923,-18,0
1716414,445222,5057676,Closed,currency 1,-1628,0,-1320.0,-1320.0,5693.625,0,57834.000,0.000,0.000,0.0,Consumer credit,-1320,NaN,5811925,-5,C
1716415,317217,5057684,Closed,currency 1,-1970,0,-1577.0,-1577.0,NaN,0,93955.500,NaN,NaN,0.0,Consumer credit,-1577,NaN,5811925,-13,C
1716416,433007,5057695,Closed,currency 1,-1100,0,-732.0,-731.0,NaN,0,98775.000,0.000,0.000,0.0,Consumer credit,-720,NaN,5811925,-24,C
1716417,433007,5057703,Active,currency 1,-740,0,31128.0,NaN,NaN,0,67500.000,2466.000,NaN,0.0,Credit card,-433,NaN,5811925,-32,C
1716418,433007,5057708,Closed,currency 1,-1389,0,-1299.0,-1299.0,0.000,0,334158.435,0.000,0.000,0.0,Consumer credit,-1299,NaN,5811925,-37,C
1716419,352790,5057718,Closed,currency 1,-1808,0,-1596.0,-1625.0,8100.000,0,28248.840,0.000,0.000,0.0,Consumer credit,-1625,NaN,5811925,-47,C
1716420,352790,5057725,Closed,currency 1,-99,0,-83.0,-98.0,NaN,0,27000.000,0.000,0.000,0.0,Consumer credit,-18,NaN,5811925,-54,C
1716421,375755,5057734,Closed,currency 1,-1335,0,-1152.0,-1152.0,NaN,0,195408.000,0.000,NaN,0.0,Consumer credit,-1139,NaN,5811925,-63,C
1716422,375755,5057742,Closed,currency 1,-2648,0,31129.0,-189.0,NaN,0,202500.000,0.000,NaN,0.0,Credit card,-109,NaN,5811925,-71,C
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.000,0,11250.000,11250.000,0.000,0.0,Microloan,-19,NaN,5811925,-79,C
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.500,0,38130.840,0.000,0.000,0.0,Consumer credit,-2493,NaN,5811925,-83,C
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.000,NaN,NaN,0.0,Consumer credit,-967,NaN,5811925,-91,C
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.000,0.000,0.000,0.0,Consumer credit,-1508,NaN,5811931,-3,C
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.000,0.000,NaN,0.0,Microloan,-387,NaN,5811931,-11,C

In [8]:
bureau.drop(['SK_ID_BUREAU_x'], axis=1, inplace=True)

In [17]:
# Splitting categorical and numeric in bureau
cat_features = [f for f in bureau.columns if bureau[f].dtype == 'object']

In [18]:
categorical_var = [x for x in bureau.columns if x in cat_features + ['SK_ID_CURR']]

In [19]:
continuous_var = [x for x in bureau.columns if x not in categorical_var]

In [20]:
bureau_1 = bureau.groupby('SK_ID_CURR').agg({k: lambda x: stats.mode(x)[0] for k in categorical_var})

In [21]:
bureau_1.head()

            SK_ID_CURR CREDIT_ACTIVE CREDIT_CURRENCY      CREDIT_TYPE STATUS
SK_ID_CURR
100001          100001        Closed      currency 1  Consumer credit      C
100002          100002        Closed      currency 1  Consumer credit      C
100003          100003        Closed      currency 1  Consumer credit      C
100004          100004        Closed      currency 1  Consumer credit      0
100005          100005        Active      currency 1  Consumer credit      4

In [26]:
bureau_2 = bureau.groupby('SK_ID_CURR').agg({k:lambda x: x.mean() for k in continuous_var})

In [27]:
bureau_2.head()

,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_BUREAU_y,MONTHS_BALANCE
SK_ID_CURR,,,,,,,,,,,,,,
100001,-735.000000,0.0,82.428571,-825.500000,NaN,0.0,207623.571429,85240.928571,0.00000,0.0,-93.142857,3545.357143,6528214.0,-14.000
100002,-874.000000,0.0,-349.000000,-697.500000,1681.029,0.0,108131.945625,49156.200000,7997.14125,0.0,-499.875000,0.000000,5291403.5,-3.625
100003,-1400.750000,0.0,-544.500000,-1097.333333,0.000,0.0,254350.125000,0.000000,202500.00000,0.0,-816.000000,NaN,6525492.0,-5.500
100004,-867.000000,0.0,-488.500000,-532.500000,0.000,0.0,94518.900000,0.000000,0.00000,0.0,-532.000000,NaN,6094383.0,-5.500
100005,-190.666667,0.0,439.333333,-123.000000,0.000,0.0,219042.000000,189469.500000,0.00000,0.0,-54.333333,1420.500000,6397934.0,-41.000

In [28]:
bureau=pd.merge(bureau_1, bureau_2, left_index=True, right_index=True)

In [29]:
bureau

,SK_ID_CURR,CREDIT_ACTIVE,CREDIT_CURRENCY,CREDIT_TYPE,STATUS,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_BUREAU_y,MONTHS_BALANCE
SK_ID_CURR,,,,,,,,,,,,,,,,,,,
100001,100001,Closed,currency 1,Consumer credit,C,-735.000000,0.0,82.428571,-825.500000,NaN,0.000000,2.076236e+05,8.524093e+04,0.000000,0.000,-93.142857,3545.357143,6.528214e+06,-14.000000
100002,100002,Closed,currency 1,Consumer credit,C,-874.000000,0.0,-349.000000,-697.500000,1681.029000,0.000000,1.081319e+05,4.915620e+04,7997.141250,0.000,-499.875000,0.000000,5.291404e+06,-3.625000
100003,100003,Closed,currency 1,Consumer credit,C,-1400.750000,0.0,-544.500000,-1097.333333,0.000000,0.000000,2.543501e+05,0.000000e+00,202500.000000,0.000,-816.000000,NaN,6.525492e+06,-5.500000
100004,100004,Closed,currency 1,Consumer credit,0,-867.000000,0.0,-488.500000,-532.500000,0.000000,0.000000,9.451890e+04,0.000000e+00,0.000000,0.000,-532.000000,NaN,6.094383e+06,-5.500000
100005,100005,Active,currency 1,Consumer credit,4,-190.666667,0.0,439.333333,-123.000000,0.000000,0.000000,2.190420e+05,1.894695e+05,0.000000,0.000,-54.333333,1420.500000,6.397934e+06,-41.000000
100007,100007,Closed,currency 1,Consumer credit,X,-1149.000000,0.0,-783.000000,-783.000000,0.000000,0.000000,1.462500e+05,0.000000e+00,0.000000,0.000,-783.000000,NaN,6.530495e+06,-11.000000
100008,100008,Closed,currency 1,Consumer credit,C,-757.333333,0.0,-391.333333,-909.000000,0.000000,0.000000,1.561485e+05,8.001900e+04,0.000000,0.000,-611.000000,NaN,6.062971e+06,-32.000000
100009,100009,Closed,currency 1,Consumer credit,C,-1271.500000,0.0,-794.937500,-1108.500000,0.000000,0.000000,2.667118e+05,7.695354e+04,0.000000,0.000,-851.611111,NaN,5.905352e+06,-14.222222
100010,100010,Active,currency 1,Consumer credit,C,-1939.500000,0.0,-119.500000,-1138.000000,NaN,0.000000,4.950000e+05,1.740038e+05,0.000000,0.000,-578.000000,NaN,6.317702e+06,-41.000000
100011,100011,Closed,currency 1,Consumer credit,0,-1773.000000,0.0,-1293.250000,-1463.250000,5073.615000,0.000000,1.088071e+05,0.000000e+00,0.000000,0.000,-1454.750000,NaN,5.089351e+06,-19.500000
100013,100013,Closed,currency 1,Car loan,X,-1737.500000,0.0,-1068.000000,-1054.750000,19305.000000,0.000000,5.180700e+05,0.000000e+00,NaN,0.000,-775.500000,0.000000,6.135121e+06,-33.750000
100014,100014,Closed,currency 1,Consumer credit,C,-1095.375000,0.0,-387.375000,-821.333333,3726.352500,0.000000,3.412416e+05,1.516428e+05,0.000000,0.000,-615.875000,NaN,5.711164e+06,-51.500000
100015,100015,Closed,currency 1,Consumer credit,C,-947.750000,0.0,-598.250000,-555.500000,NaN,0.000000,1.023739e+05,0.000000e+00,0.000000,0.000,-551.250000,NaN,6.010841e+06,-36.500000
100016,100016,Active,currency 1,Consumer credit,C,-618.428571,0.0,-217.142857,-929.666667,0.000000,0.000000,6.785486e+04,1.274490e+04,0.000000,0.000,-405.857143,NaN,5.788133e+06,-4.000000
100017,100017,Closed,currency 1,Consumer credit,C,-1944.333333,0.0,-1512.333333,-1677.833333,0.000000,0.000000,1.432950e+05,0.000000e+00,0.000000,0.000,-1594.333333,NaN,6.093949e+06,-72.500000
100019,100019,Active,currency 1,Consumer credit,C,-495.000000,0.0,5441.000000,NaN,0.000000,0.000000,3.600000e+05,1.227351e+05,135000.000000,0.000,-26.500000,27000.000000,6.525120e+06,-32.500000
100020,100020,Active,currency 1,Consumer credit,0,-261.500000,0.0,-32.500000,-223.000000,0.000000,0.000000,4.987125e+04,3.077212e+04,0.000000,0.000,-130.750000,NaN,6.407362e+06,-11.500000
100022,100022,Active,currency 1,Consumer credit,X,-337.000000,0.0,940.000000,NaN,0.000000,0.000000,5.287500e+05,2.052765e+05,0.000000,0.000,-28.000000,NaN,6.451338e+06,-80.500000
100023,100023,Closed,currency 1,Consumer credit,C,-1164.384615,0.0,-364.916667,-997.300000,2720.850000,0.000000,1.265917e+05,1.370385e+04,0.000000,0.000,-634.076923,NaN,6.308389e+06,-9.769231
100025,100025,Active,currency 1,Consumer credit,C,-700.000000,0.0,1124.000000,NaN,NaN,0.000000,2.452500e+06,1.886544e+06,0.000000,0.000,-49.000000,NaN,5.945856e+06,-36.000000
100026,100026,Active,currency 1,Consumer credit,0,-679.000000,0.0,899.000000,-916.000000,0.000000,0.000000,1.875000e+06,1.738907e+06,0.000000,0.000,-314.666667,NaN,6.361016e+06,-9.000000
100027,100027,Closed,currency 1,Consumer credit,0,-793.000000,0.0,-278.333333,-902.500000,2565.000000,0.000000,2.084325e+05,1.255710e+05,0.000000,0.000,-600.666667,NaN,6.438550e+06,-21.000000
100028,100028,Closed,currency 1,Consumer credit,X,-1401.750000,0.0,2387.700000,-1238.285714,0.000000,0.000000,1.267396e+05,1.863045e+04,14484.394286,0.000,-651.500000,3012.010714,6.014969e+06,-48.500000
100029,100029,Closed,currency 1,Consumer credit,C,-1416.750000,0.0,-336.333333,-1541.333333,NaN,0.000000,1.857008e+06,1.227429e+06,0.000000,0.000,-1041.750000,NaN,5.899167e+06,-70.500000
100030,100030,Closed,currency 1,Consumer credit,C,-930.833333,0.0,-61.600000,-624.000000,0.000000,0.000000,1.072385e+05,7.527375e+04,4276.005000,0.000,-411.166667,NaN,5.971008e+06,-48.500000
100031,100031,Closed,currency 1,Consumer credit,X,-579.571429,0.0,468.600000,-449.000000,NaN,0.000000,5.672359e+05,5.625000e+05,NaN,0.000,-266.285714,NaN,5.945858e+06,-19.000000
100032,100032,Closed,currency 1,Consumer credit,0,-1071.000000,0.0,-525.250000,-636.666667,0.000000,0.000000,3.177900e+05,0.000000e+00,0.000000,0.000,-436.750000,17437.500000,5.236540e+06,-12.500000
100033,100033,Active,currency 1,Credit card,0,-195.000000,0.0,913.000000,NaN,NaN,0.000000,6.750000e+05,0.000000e+00,0.000000,0.000,-169.000000,NaN,6.835303e+06,-42.000000
100035,100035,Active,currency 1,Consumer credit,0,-1399.333333,0.0,487.000000,-2023.750000,13760.066250,0.000000,3.938984e+05,4.108743e+05,0.000000,0.000,-915.333333,NaN,5.822705e+06,-64.000000
100036,100036,Active,currency 1,Consumer credit,C,-889.000000,0.0,-462.000000,NaN,NaN,0.000000,9.495900e+04,8.339355e+03,NaN,0.000,-519.000000,NaN,6.546377e+06,-20.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456220,456220,Closed,currency 1,Consumer credit,C,-1000.800000,0.0,5134.000000,-1076.666667,0.000000,0.400000,1.660680e+05,1.175350e+05,57551.145000,0.000,-458.800000,NaN,5.010220e+06,-24.000000
456221,456221,Closed,currency 1,Consumer credit,0,-727.200000,0.0,7.000000,-457.666667,11427.750000,0.000000,2.237598e+05,1.112940e+05,0.000000,0.000,-282.200000,5960.700000,5.477894e+06,-32.000000
456223,456223,Closed,currency 1,Consumer credit,0,-539.000000,0.0,-382.250000,-412.750000,0.000000,0.000000,4.312619e+05,4.268700e+03,7300.687500,0.000,-308.400000,1263.375000,5.177953e+06,-54.000000
456224,456224,Closed,currency 1,Consumer credit,0,-1755.823529,0.0,-865.875000,-1530.909091,1492.488000,0.000000,2.263932e+05,5.251190e+04,0.000000,0.000,-907.823529,4608.450000,5.227653e+06,-13.588235
456225,456225,Active,currency 1,Consumer credit,X,-1053.000000,0.0,253.125000,-714.000000,NaN,0.000000,4.126880e+05,3.996357e+05,11822.460000,0.000,-174.333333,NaN,5.722776e+06,-16.888889
456226,456226,Active,currency 1,Credit card,X,-455.000000,0.0,514.000000,NaN,NaN,0.000000,2.250000e+05,2.550600e+04,0.000000,0.000,-15.500000,NaN,5.542590e+06,-19.500000
456227,456227,Active,currency 1,Consumer credit,0,-1596.250000,0.0,-726.250000,-1305.000000,4680.000000,0.000000,1.993106e+05,5.231700e+04,0.000000,0.000,-964.250000,NaN,6.263651e+06,-36.500000
456229,456229,Active,currency 1,Credit card,C,-1839.000000,0.0,9118.000000,NaN,11353.500000,1.000000,2.587500e+05,NaN,NaN,0.000,-43.000000,NaN,6.107296e+06,-33.000000
456230,456230,Closed,currency 1,Consumer credit,C,-1254.833333,1.0,2025.200000,-1091.000000,0.000000,0.000000,1.163869e+05,2.532027e+04,0.000000,17.625,-626.000000,16089.942857,6.448592e+06,-8.416667
456231,456231,Closed,currency 1,Consumer credit,C,-712.285714,0.0,536.714286,-529.500000,NaN,0.000000,4.733479e+05,1.407780e+05,0.000000,0.000,-190.142857,14832.000000,6.380477e+06,-21.428571
456232,456232,Active,currency 1,Consumer credit,0,-529.500000,0.0,506.000000,NaN,NaN,0.000000,4.005000e+05,2.586712e+05,0.000000,0.000,-28.000000,NaN,6.259244e+06,-17.000000
456233,456233,Active,currency 1,Consumer credit,X,-203.000000,0.0,528.000000,NaN,0.000000,0.000000,2.826633e+05,2.239439e+05,0.000000,0.000,-20.000000,7537.500000,6.066021e+06,-26.000000
456234,456234,Closed,currency 1,Consumer credit,C,-756.600000,0.0,-205.100000,-701.714286,10364.122500,0.000000,1.393960e+05,2.452031e+03,64.297500,0.000,-507.300000,13125.015000,6.023547e+06,-48.300000
456235,456235,Closed,currency 1,Consumer credit,X,-1785.000000,0.0,1381.333333,-1243.500000,0.000000,0.000000,4.930500e+05,3.866790e+05,0.000000,0.000,-727.666667,NaN,5.139351e+06,-11.000000
456236,456236,Closed,currency 1,Consumer credit,C,-1270.153846,0.0,478.769231,-1343.888889,2805.545455,0.000000,6.389756e+05,4.420797e+05,0.000000,0.000,-946.153846,NaN,6.450944e+06,-65.000000
456237,456237,Closed,currency 1,Consumer credit,X,-1430.000000,0.0,-699.000000,-1090.000000,NaN,0.000000,9.814500e+04,0.000000e+00,0.000000,0.000,-1090.000000,NaN,5.615274e+06,-44.000000
456238,456238,Closed,currency 1,Consumer credit,C,-2157.833333,0.0,-1561.666667,-2362.500000,3191.737500,0.000000,1.849170e+05,1.042252e+05,0.000000,0.000,-1579.333333,6600.000000,6.309329e+06,-12.500000
456239,456239,Closed,currency 1,Consumer credit,0,-1529.909091,0.0,333.000000,-1534.166667,0.000000,0.000000,5.693011e+05,3.809529e+05,0.000000,0.000,-770.000000,NaN,6.580146e+06,-63.000000
456240,456240,Active,currency 1,Consumer credit,C,-1438.500000,0.0,12425.000000,-2464.000000,3996.000000,0.000000,6.619950e+04,3.987225e+04,50127.750000,0.000,-1238.500000,NaN,5.489732e+06,-17.500000
456241,456241,Closed,currency 1,Consumer credit,C,-1599.200000,0.0,-1623.000000,-695.666667,NaN,0.000000,2.430000e+05,0.000000e+00,0.000000,0.000,-1096.600000,NaN,6.015713e+06,-73.800000
456242,456242,Active,currency 1,Credit card,X,-491.000000,0.0,509.000000,NaN,NaN,0.000000,1.980000e+05,1.860975e+05,0.000000,0.000,-5.000000,11205.000000,6.528612e+06,-17.000000
456243,456243,Closed,currency 1,Consumer credit,0,-710.571429,0.0,-459.400000,-455.000000,0.000000,0.000000,2.553962e+05,3.118635e+05,0.000000,0.000,-338.285714,NaN,6.567329e+06,-38.000000
456244,456244,Closed,currency 1,Consumer credit,X,-1740.956522,0.0,-1132.090909,-1480.578947,7602.390000,0.000000,3.264789e+05,4.704964e+04,44.553750,0.000,-1209.826087,10298.250000,5.476677e+06,-33.521739
456246,456246,Closed,currency 1,Consumer credit,C,-1361.000000,0.0,-234.666667,-1331.000000,NaN,0.000000,1.275000e+05,0.000000e+00,0.000000,0.000,-373.333333,NaN,6.809761e+06,-36.000000
456247,456247,Closed,currency 1,Consumer credit,C,-1043.181818,0.0,1449.818182,-1085.000000,5932.676250,0.090909,4.714057e+05,3.655650e+05,0.000000,0.000,-768.818182,6227.357143,6.326207e+06,-21.727273
456249,456249,Closed,currency 1,Consumer credit,0,-1667.076923,0.0,-1232.333333,-1364.750000,6147.000000,0.000000,2.841430e+05,1.630710e+04,0.000000,0.000,-1064.538462,NaN,6.625568e+06,-30.615385
456250,456250,Active,currency 1,Consumer credit,C,-862.000000,0.0,1288.333333,-760.000000,0.000000,0.000000,1.028820e+06,7.440134e+05,19422.795000,0.000,-60.333333,154567.965000,6.406505e+06,-10.666667
456253,456253,Active,currency 1,Consumer credit,X,-867.500000,0.0,280.500000,-794.000000,NaN,0.000000,9.900000e+05,4.489582e+05,0.000000,0.000,-253.250000,58369.500000,6.016483e+06,-48.750000
456254,456254,Closed,currency 1,Consumer credit,0,-1104.000000,0.0,-859.000000,-859.000000,NaN,0.000000,4.500000e+04,0.000000e+00,NaN,0.000,-401.000000,0.000000,6.143524e+06,-76.000000
456255,456255,Closed,currency 1,Consumer credit,0,-1089.454545,0.0,3231.272727,-968.333333,12056.481000,0.090909,3.456290e+05,1.918641e+05,0.000000,0.000,-531.090909,1081.500000,6.566372e+06,-12.000000

In [30]:
bureau.drop(['SK_ID_BUREAU_y'], axis=1, inplace=True)

In [31]:
bureau.drop(['SK_ID_CURR'], axis=1, inplace=True)

In [32]:
bureau

,CREDIT_ACTIVE,CREDIT_CURRENCY,CREDIT_TYPE,STATUS,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,MONTHS_BALANCE
SK_ID_CURR,,,,,,,,,,,,,,,,,
100001,Closed,currency 1,Consumer credit,C,-735.000000,0.0,82.428571,-825.500000,NaN,0.000000,2.076236e+05,8.524093e+04,0.000000,0.000,-93.142857,3545.357143,-14.000000
100002,Closed,currency 1,Consumer credit,C,-874.000000,0.0,-349.000000,-697.500000,1681.029000,0.000000,1.081319e+05,4.915620e+04,7997.141250,0.000,-499.875000,0.000000,-3.625000
100003,Closed,currency 1,Consumer credit,C,-1400.750000,0.0,-544.500000,-1097.333333,0.000000,0.000000,2.543501e+05,0.000000e+00,202500.000000,0.000,-816.000000,NaN,-5.500000
100004,Closed,currency 1,Consumer credit,0,-867.000000,0.0,-488.500000,-532.500000,0.000000,0.000000,9.451890e+04,0.000000e+00,0.000000,0.000,-532.000000,NaN,-5.500000
100005,Active,currency 1,Consumer credit,4,-190.666667,0.0,439.333333,-123.000000,0.000000,0.000000,2.190420e+05,1.894695e+05,0.000000,0.000,-54.333333,1420.500000,-41.000000
100007,Closed,currency 1,Consumer credit,X,-1149.000000,0.0,-783.000000,-783.000000,0.000000,0.000000,1.462500e+05,0.000000e+00,0.000000,0.000,-783.000000,NaN,-11.000000
100008,Closed,currency 1,Consumer credit,C,-757.333333,0.0,-391.333333,-909.000000,0.000000,0.000000,1.561485e+05,8.001900e+04,0.000000,0.000,-611.000000,NaN,-32.000000
100009,Closed,currency 1,Consumer credit,C,-1271.500000,0.0,-794.937500,-1108.500000,0.000000,0.000000,2.667118e+05,7.695354e+04,0.000000,0.000,-851.611111,NaN,-14.222222
100010,Active,currency 1,Consumer credit,C,-1939.500000,0.0,-119.500000,-1138.000000,NaN,0.000000,4.950000e+05,1.740038e+05,0.000000,0.000,-578.000000,NaN,-41.000000
100011,Closed,currency 1,Consumer credit,0,-1773.000000,0.0,-1293.250000,-1463.250000,5073.615000,0.000000,1.088071e+05,0.000000e+00,0.000000,0.000,-1454.750000,NaN,-19.500000
100013,Closed,currency 1,Car loan,X,-1737.500000,0.0,-1068.000000,-1054.750000,19305.000000,0.000000,5.180700e+05,0.000000e+00,NaN,0.000,-775.500000,0.000000,-33.750000
100014,Closed,currency 1,Consumer credit,C,-1095.375000,0.0,-387.375000,-821.333333,3726.352500,0.000000,3.412416e+05,1.516428e+05,0.000000,0.000,-615.875000,NaN,-51.500000
100015,Closed,currency 1,Consumer credit,C,-947.750000,0.0,-598.250000,-555.500000,NaN,0.000000,1.023739e+05,0.000000e+00,0.000000,0.000,-551.250000,NaN,-36.500000
100016,Active,currency 1,Consumer credit,C,-618.428571,0.0,-217.142857,-929.666667,0.000000,0.000000,6.785486e+04,1.274490e+04,0.000000,0.000,-405.857143,NaN,-4.000000
100017,Closed,currency 1,Consumer credit,C,-1944.333333,0.0,-1512.333333,-1677.833333,0.000000,0.000000,1.432950e+05,0.000000e+00,0.000000,0.000,-1594.333333,NaN,-72.500000
100019,Active,currency 1,Consumer credit,C,-495.000000,0.0,5441.000000,NaN,0.000000,0.000000,3.600000e+05,1.227351e+05,135000.000000,0.000,-26.500000,27000.000000,-32.500000
100020,Active,currency 1,Consumer credit,0,-261.500000,0.0,-32.500000,-223.000000,0.000000,0.000000,4.987125e+04,3.077212e+04,0.000000,0.000,-130.750000,NaN,-11.500000
100022,Active,currency 1,Consumer credit,X,-337.000000,0.0,940.000000,NaN,0.000000,0.000000,5.287500e+05,2.052765e+05,0.000000,0.000,-28.000000,NaN,-80.500000
100023,Closed,currency 1,Consumer credit,C,-1164.384615,0.0,-364.916667,-997.300000,2720.850000,0.000000,1.265917e+05,1.370385e+04,0.000000,0.000,-634.076923,NaN,-9.769231
100025,Active,currency 1,Consumer credit,C,-700.000000,0.0,1124.000000,NaN,NaN,0.000000,2.452500e+06,1.886544e+06,0.000000,0.000,-49.000000,NaN,-36.000000
100026,Active,currency 1,Consumer credit,0,-679.000000,0.0,899.000000,-916.000000,0.000000,0.000000,1.875000e+06,1.738907e+06,0.000000,0.000,-314.666667,NaN,-9.000000
100027,Closed,currency 1,Consumer credit,0,-793.000000,0.0,-278.333333,-902.500000,2565.000000,0.000000,2.084325e+05,1.255710e+05,0.000000,0.000,-600.666667,NaN,-21.000000
100028,Closed,currency 1,Consumer credit,X,-1401.750000,0.0,2387.700000,-1238.285714,0.000000,0.000000,1.267396e+05,1.863045e+04,14484.394286,0.000,-651.500000,3012.010714,-48.500000
100029,Closed,currency 1,Consumer credit,C,-1416.750000,0.0,-336.333333,-1541.333333,NaN,0.000000,1.857008e+06,1.227429e+06,0.000000,0.000,-1041.750000,NaN,-70.500000
100030,Closed,currency 1,Consumer credit,C,-930.833333,0.0,-61.600000,-624.000000,0.000000,0.000000,1.072385e+05,7.527375e+04,4276.005000,0.000,-411.166667,NaN,-48.500000
100031,Closed,currency 1,Consumer credit,X,-579.571429,0.0,468.600000,-449.000000,NaN,0.000000,5.672359e+05,5.625000e+05,NaN,0.000,-266.285714,NaN,-19.000000
100032,Closed,currency 1,Consumer credit,0,-1071.000000,0.0,-525.250000,-636.666667,0.000000,0.000000,3.177900e+05,0.000000e+00,0.000000,0.000,-436.750000,17437.500000,-12.500000
100033,Active,currency 1,Credit card,0,-195.000000,0.0,913.000000,NaN,NaN,0.000000,6.750000e+05,0.000000e+00,0.000000,0.000,-169.000000,NaN,-42.000000
100035,Active,currency 1,Consumer credit,0,-1399.333333,0.0,487.000000,-2023.750000,13760.066250,0.000000,3.938984e+05,4.108743e+05,0.000000,0.000,-915.333333,NaN,-64.000000
100036,Active,currency 1,Consumer credit,C,-889.000000,0.0,-462.000000,NaN,NaN,0.000000,9.495900e+04,8.339355e+03,NaN,0.000,-519.000000,NaN,-20.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456220,Closed,currency 1,Consumer credit,C,-1000.800000,0.0,5134.000000,-1076.666667,0.000000,0.400000,1.660680e+05,1.175350e+05,57551.145000,0.000,-458.800000,NaN,-24.000000
456221,Closed,currency 1,Consumer credit,0,-727.200000,0.0,7.000000,-457.666667,11427.750000,0.000000,2.237598e+05,1.112940e+05,0.000000,0.000,-282.200000,5960.700000,-32.000000
456223,Closed,currency 1,Consumer credit,0,-539.000000,0.0,-382.250000,-412.750000,0.000000,0.000000,4.312619e+05,4.268700e+03,7300.687500,0.000,-308.400000,1263.375000,-54.000000
456224,Closed,currency 1,Consumer credit,0,-1755.823529,0.0,-865.875000,-1530.909091,1492.488000,0.000000,2.263932e+05,5.251190e+04,0.000000,0.000,-907.823529,4608.450000,-13.588235
456225,Active,currency 1,Consumer credit,X,-1053.000000,0.0,253.125000,-714.000000,NaN,0.000000,4.126880e+05,3.996357e+05,11822.460000,0.000,-174.333333,NaN,-16.888889
456226,Active,currency 1,Credit card,X,-455.000000,0.0,514.000000,NaN,NaN,0.000000,2.250000e+05,2.550600e+04,0.000000,0.000,-15.500000,NaN,-19.500000
456227,Active,currency 1,Consumer credit,0,-1596.250000,0.0,-726.250000,-1305.000000,4680.000000,0.000000,1.993106e+05,5.231700e+04,0.000000,0.000,-964.250000,NaN,-36.500000
456229,Active,currency 1,Credit card,C,-1839.000000,0.0,9118.000000,NaN,11353.500000,1.000000,2.587500e+05,NaN,NaN,0.000,-43.000000,NaN,-33.000000
456230,Closed,currency 1,Consumer credit,C,-1254.833333,1.0,2025.200000,-1091.000000,0.000000,0.000000,1.163869e+05,2.532027e+04,0.000000,17.625,-626.000000,16089.942857,-8.416667
456231,Closed,currency 1,Consumer credit,C,-712.285714,0.0,536.714286,-529.500000,NaN,0.000000,4.733479e+05,1.407780e+05,0.000000,0.000,-190.142857,14832.000000,-21.428571
456232,Active,currency 1,Consumer credit,0,-529.500000,0.0,506.000000,NaN,NaN,0.000000,4.005000e+05,2.586712e+05,0.000000,0.000,-28.000000,NaN,-17.000000
456233,Active,currency 1,Consumer credit,X,-203.000000,0.0,528.000000,NaN,0.000000,0.000000,2.826633e+05,2.239439e+05,0.000000,0.000,-20.000000,7537.500000,-26.000000
456234,Closed,currency 1,Consumer credit,C,-756.600000,0.0,-205.100000,-701.714286,10364.122500,0.000000,1.393960e+05,2.452031e+03,64.297500,0.000,-507.300000,13125.015000,-48.300000
456235,Closed,currency 1,Consumer credit,X,-1785.000000,0.0,1381.333333,-1243.500000,0.000000,0.000000,4.930500e+05,3.866790e+05,0.000000,0.000,-727.666667,NaN,-11.000000
456236,Closed,currency 1,Consumer credit,C,-1270.153846,0.0,478.769231,-1343.888889,2805.545455,0.000000,6.389756e+05,4.420797e+05,0.000000,0.000,-946.153846,NaN,-65.000000
456237,Closed,currency 1,Consumer credit,X,-1430.000000,0.0,-699.000000,-1090.000000,NaN,0.000000,9.814500e+04,0.000000e+00,0.000000,0.000,-1090.000000,NaN,-44.000000
456238,Closed,currency 1,Consumer credit,C,-2157.833333,0.0,-1561.666667,-2362.500000,3191.737500,0.000000,1.849170e+05,1.042252e+05,0.000000,0.000,-1579.333333,6600.000000,-12.500000
456239,Closed,currency 1,Consumer credit,0,-1529.909091,0.0,333.000000,-1534.166667,0.000000,0.000000,5.693011e+05,3.809529e+05,0.000000,0.000,-770.000000,NaN,-63.000000
456240,Active,currency 1,Consumer credit,C,-1438.500000,0.0,12425.000000,-2464.000000,3996.000000,0.000000,6.619950e+04,3.987225e+04,50127.750000,0.000,-1238.500000,NaN,-17.500000
456241,Closed,currency 1,Consumer credit,C,-1599.200000,0.0,-1623.000000,-695.666667,NaN,0.000000,2.430000e+05,0.000000e+00,0.000000,0.000,-1096.600000,NaN,-73.800000
456242,Active,currency 1,Credit card,X,-491.000000,0.0,509.000000,NaN,NaN,0.000000,1.980000e+05,1.860975e+05,0.000000,0.000,-5.000000,11205.000000,-17.000000
456243,Closed,currency 1,Consumer credit,0,-710.571429,0.0,-459.400000,-455.000000,0.000000,0.000000,2.553962e+05,3.118635e+05,0.000000,0.000,-338.285714,NaN,-38.000000
456244,Closed,currency 1,Consumer credit,X,-1740.956522,0.0,-1132.090909,-1480.578947,7602.390000,0.000000,3.264789e+05,4.704964e+04,44.553750,0.000,-1209.826087,10298.250000,-33.521739
456246,Closed,currency 1,Consumer credit,C,-1361.000000,0.0,-234.666667,-1331.000000,NaN,0.000000,1.275000e+05,0.000000e+00,0.000000,0.000,-373.333333,NaN,-36.000000
456247,Closed,currency 1,Consumer credit,C,-1043.181818,0.0,1449.818182,-1085.000000,5932.676250,0.090909,4.714057e+05,3.655650e+05,0.000000,0.000,-768.818182,6227.357143,-21.727273
456249,Closed,currency 1,Consumer credit,0,-1667.076923,0.0,-1232.333333,-1364.750000,6147.000000,0.000000,2.841430e+05,1.630710e+04,0.000000,0.000,-1064.538462,NaN,-30.615385
456250,Active,currency 1,Consumer credit,C,-862.000000,0.0,1288.333333,-760.000000,0.000000,0.000000,1.028820e+06,7.440134e+05,19422.795000,0.000,-60.333333,154567.965000,-10.666667
456253,Active,currency 1,Consumer credit,X,-867.500000,0.0,280.500000,-794.000000,NaN,0.000000,9.900000e+05,4.489582e+05,0.000000,0.000,-253.250000,58369.500000,-48.750000
456254,Closed,currency 1,Consumer credit,0,-1104.000000,0.0,-859.000000,-859.000000,NaN,0.000000,4.500000e+04,0.000000e+00,NaN,0.000,-401.000000,0.000000,-76.000000
456255,Closed,currency 1,Consumer credit,0,-1089.454545,0.0,3231.272727,-968.333333,12056.481000,0.090909,3.456290e+05,1.918641e+05,0.000000,0.000,-531.090909,1081.500000,-12.000000

In [34]:
bureau.to_csv('bureau_b_bal.csv', index = False)