In [1]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

from sklearn.ensemble import VotingClassifier
from sklearn.metrics import roc_auc_score
import pandas as pd

In [2]:
merged_train =pd.read_csv('C:\\home-credit-default-risk\\imputed_train.csv')

In [3]:
merged_test =pd.read_csv('C:\\home-credit-default-risk\\imputed_test.csv')

In [20]:
merged_test.head()

,AMT_ANNUITY,AMT_ANNUITY_x,AMT_ANNUITY_y,AMT_APPLICATION,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_CREDIT_MAX_OVERDUE,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,...,WEEKDAY_APPR_PROCESS_START_TUESDAY.1,WEEKDAY_APPR_PROCESS_START_WEDNESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY.1,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_AVG,YEARS_BUILD_MEDI,YEARS_BUILD_MODE,SK_ID_CURR
0,1236.244186,20560.5,3951.000,24835.50,16381.567500,145843.373494,0.0,161516.250000,23893.770349,0.000000,...,0.0,0.0,0.0,0.9732,0.9732,0.9732,0.7552,0.7585,0.7583,100001
1,608.785714,17370.0,4813.200,22308.75,16381.567500,145843.373494,0.0,175903.714286,132923.785714,0.000000,...,0.0,0.0,0.0,0.9816,0.9816,0.9816,0.7552,0.7585,0.7583,100005
2,0.000000,69777.0,11478.195,130871.25,18159.919219,131718.750000,19305.0,532530.923478,0.000000,0.000000,...,0.0,1.0,1.0,0.9816,0.9816,0.9816,0.7552,0.7585,0.7583,100013
3,1191.480605,49018.5,8091.585,49207.50,8085.058163,225000.000000,0.0,110187.861107,4962.624477,2934.137749,...,0.0,0.0,0.0,0.9970,0.9970,0.9970,0.9592,0.9597,0.9608,100028
4,4189.362245,32067.0,17782.155,267727.50,16381.567500,145843.373494,0.0,183811.058824,25415.566390,0.000000,...,1.0,0.0,0.0,0.9816,0.9816,0.9816,0.7552,0.7585,0.7583,100038

In [4]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [5]:
dtc = DecisionTreeClassifier(random_state=2019)
logreg = LogisticRegression()
gauss = GaussianNB()

In [6]:
Voting = VotingClassifier(estimators=[('DT',dtc),
                                      ('LR',logreg),
                                      ('GU',gauss)],voting='soft')

In [7]:
X = merged_train.iloc[:,0:464]
y = merged_train[['TARGET']]

In [34]:
Voting.fit(X,y)

C:\Users\dbda\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dbda\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dbda\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

VotingClassifier(estimators=[('DT',
                              DecisionTreeClassifier(class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort=False,
                                                     random_state=2019,
                                                     splitter='best')),
                             ('LR',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('GU',
                              GaussianNB(priors=None, var_smoothing=1e-09))],
                 flatten_transform=True, n_jobs=None, voting='soft',
                 weights=None)

In [45]:
y_pred = Voting.predict_proba(test)[:,1]

In [39]:
submission = pd.DataFrame({'SK_ID_CURR': merged_test['SK_ID_CURR'], 'TARGET': y_pred})

In [40]:
submission.to_csv('C:\\home-credit-default-risk\\result\\voting_classifier.csv', index = False)